### PR TITLE
Update Working Group Info

### PR DESCRIPTION
**Pull request by gtfierro**
Update times, add Google Calendar links

### CODE REVIEW

**Comment by epaulson** [comment]
This doesn't look like it got deployed?

**Comment by gtfierro** [comment]
@shreyasnagare the server is running out of memory when it is attempting to build the website. The last part of the log I see before the stacktrace is

```
Load sources - 1.3s
Create GraphQL schema - 0.54s
Create pages and templates - 1.01s
Generate temporary code - 3.09s
Bootstrap finish - 6.78s
Compiling assets...
Compile assets - 20.82s
Execute GraphQL (4258 queries) - 52.9s

<--- Last few GCs --->

[11850:0x5815380]   204334 ms: Scavenge 2024.1 (2083.1) -> 2019.6 (2083.8) MB, 5.8 / 0.1 ms  (average mu = 0.794, current mu = 0.688) task
[11850:0x5815380]   204479 ms: Scavenge 2024.8 (2083.8) -> 2020.9 (2085.6) MB, 6.5 / 0.0 ms  (average mu = 0.794, current mu = 0.688) task
[11850:0x5815380]   205679 ms: Mark-sweep 2029.7 (2087.3) -> 2016.5 (2089.1) MB, 1111.3 / 0.1 ms  (average mu = 0.676, current mu = 0.477) allocation failure scavenge might not succeed


<--- JS stacktrace --->
```

**Comment by shreyasnagare** [comment]
Although the generator is building about 8-9k HTML pages, most of this is done in a sequential manner and I'm not sure if this would need more than 512 MBs of memory (default). I've bumped the max heap space to 2 GBs so this shouldn't be a problem now.

So instead of using `npm run build` in the deployment script, we're now using 
`node --max-old-space-size=2048 node_modules/gridsome/bin/gridsome.js build` 
which allows us to use node's default cli-args too.

**Comment by gtfierro** [comment]
Thanks for the fix!

**Pull request merged**
