### PR TITLE
Add Brick 1.2.1

### PR DESCRIPTION
**Pull request by shreyasnagare**
- [x] Enables SHACL property based docs for all Classes.
- [x] Updates Brick `v1.2` docs + TTL (v1.2.1)

Notes:
- Brick `v1.2.0` and `v1.2.1` TTL files will be accessible through `https://brickschema.org/schema/<version>/Brick#`.

### CODE REVIEW

**Comment by gtfierro** [comment]
The documentation looks to be correct; there are a couple more things that we need to change in the website:
- point to v1.2.1 on the resources page and move 1.2.0 to th "past releases" list
- add the v1.2.1 release notes to the ontology description page in the v1.2.1 ontology documentation

I can handle those tonight if this is something you don't have time to add to this PR --- just let me know. Thanks for getting this together!

**Review by gtfierro — APPROVED** [review]
Thanks!

**Comment by shreyasnagare** [comment]
I think the `v1.2` ontologyPage should highlight all the changes since the last `v1.1` patch release. Same thing for `v1.1` ontologyPage. What do you think? Something like:

## Release Notes 

### v1.2.1

Brick v1.2.1 is the latest patch release of Brick since v1.2.0 in February 2021. It incorporates a variety of quality of life changes, bug fixes, class additions and other changes to increase the consistency, usability and correctness of Brick. These include, but are not limited to:

- An expanded set of [entity properties](https://docs.brickschema.org/metadata/entity-properties.html) with expanded sets of available units
- Extensions to the ontology covering items such as:
  - differential quantities (i.e. "differential temperature")
  - expanded electrical points
  - radiant systems equipment and points
  - photovoltaic systems
  - collection types, such as systems and loops
- Improved and expanded examples in the `examples/` folder, which are now validated as part of the integration testing process
- Various typos, missing annotations, etc

### v1.2.0

Brick v1.2.0 marks just over 7 months of work from a growing community of contributors. Moving forward, Brick will be targeting a 6 month cycle for "minor" releases (e.g. `Brick v1.x.y`). The Brick development roadmap can be found at http://roadmap.brickschema.org/ . The Brick community is always looking for more volunteers to provide feedback and contribute features to Brick.

Brick v1.2.0 brings a number of new features. If you are using the [brickschema Python package](https://brickschema.readthedocs.io/en/latest/) please be sure to update to `brickschema>=0.3.0`.

- **Namespace change** (hopefully for the last time): to facilitate future development of Brick, Brick is changing its namespace to *no longer contain a version number*. Brick can still be downloaded on a per-version basis in the future, but to aid in the adoption of future (backwards-compatible) versions of Brick, it was decided that the best course of action was to remove the need to increment version numbers. This way, only a new copy of the Brick graph needs to be loaded in order to upgrade
    - Old namespace (v1.1.x): `https://brickschema.org/schema/1.1/Brick#`
    - **New namespace (v1.2.x and onward)**: `https://brickschema.org/schema/Brick#`
- **Entity Properties**: entity properties are a new Brick feature (described in-depth [here](https://docs.brickschema.org/metadata/entity-properties.html)) that allow models to attach static properties to Brick entities. The initial release of entity properties include floor area (net and gross), electrical metering properties, and aggregations. Documentation for entity properties on the Brick website is coming soon
- **Timeseries Storage**: the 1.2.0 release also includes some preliminary timeseries storage properties. See [here](https://docs.brickschema.org/metadata/timeseries-storage.html) for documentation; please file an issue or post on the mailing list to discuss any emergent modeling needs for timeseries
- **Alignments**: Brick 1.2.0 also includes [alignments](https://github.com/BrickSchema/Brick/tree/master/alignments) with several external ontologies and metadata representations
    - [BOT](https://w3c-lbd-cg.github.io/bot/): an ontology for building topologies and locations
    - [VBIS](https://vbis.com.au/): an emerging standard for asset management tagging
    - [REC](https://www.realestatecore.io/): an emerging ontology for real estate management
- **Additional classes**:
    - Locations: A large number of standard room use types have been added to Brick
    - Chiller Plants (more coming): A number of Chiller-related points and equipment have been added to Brick. Future discussions on chillers should be directed to https://github.com/BrickSchema/Brick/issues/197

**Comment by gtfierro** [comment]
Oh, yeah; this is much better! Good idea

**Comment by gtfierro** [comment]
I'm ok with you merging this whenever you are ready

**Comment by shreyasnagare** [comment]
> Oh, yeah; this is much better! Good idea

Since there are no release notes for [`v1.1.1` release](https://github.com/BrickSchema/Brick/compare/v1.1.0...v1.1.1), I've only added `v1.1.0` notes to the ontologyPage for `v1.1` .

**Pull request merged**
