### PR TITLE
Restructuring the resources page

### PR DESCRIPTION
**Pull request by gtfierro**
Changes + questions

- reformatted the "Brick distribution" section so its a little more compact. When we have more releases of Brick, it may make sense to have a separate page for the distributions, but I think this works for now
- publications: I added the ones I could find, but *please* let me know if I've left any Brick publications out!
- building reference models: We have to add whitespace after every line in order to get the formatting correct, which is a little awkward. Is there a more compact tabular form we can use? What do people think?
- presentations: do we want to add links to the slides we have used for the talks? 
- static files: is there a way we can include the PDF files in this repository rather than linking to external copies? I wasn't sure how to link to static files using the markdown setup; my initial attempts didn't seem to work

### CODE REVIEW

**Comment by shreyasnagare** [comment]
Here are some suggestions which I can work on (while you work on the content) **if you like them**:

## Brick Distribution
This looks perfectly fine to me.

## Reference Brick Models
I was thinking the same thing. A table would certainly make this look better. I think we might have to list the buildings, their download links(hyperlinks on the names), and their **locations** (location might take a lot of space in the table) above the "Details" table (mostly numbers). Or not. What do you think?

## Academic Publications
- If we are not putting the publications in the reverse chronological order, we should at least put the year/venue right next to the title.
- We could use formatting options to separate the title, the venue, and the authors.
- We should have subheadings to separate the publications about the core schema from the other publications (about systems that work with/around Brick).

[Brick: Towards a Unified Metadata Schema For Buildings][6]. Bharathan Balaji, Arka Bhattacharya, Gabriel Fierro, Jingkun Gao, Joshua Gluck, Dezhi Hong, Aslak Johansen, Jason Koh, Joern Ploennigs, Yuvraj Agarwal, Mario Berges, David Culler, Rajesh Gupta, Mikkel Baun Kjærgaard, Mani Srivastava, and Kamin Whitehouse. 2016. In Proceedings of the 3rd ACM International Conference on Systems for Energy-Efficient Built Environments (BuildSys 2016). DOI: https://doi.org/10.1145/2993422.2993577 

>[Brick: Towards a Unified Metadata Schema For Buildings][6] - 2016. 
>*In Proceedings of the 3rd ACM International Conference on Systems for Energy-Efficient Built Environments (**BuildSys 2016**).
>DOI: https://doi.org/10.1145/2993422.2993577*
>Bharathan Balaji, Arka Bhattacharya, Gabriel Fierro, Jingkun Gao, Joshua Gluck, Dezhi Hong, Aslak Johansen, Jason Koh, Joern Ploennigs, Yuvraj Agarwal, Mario Berges, David Culler, Rajesh Gupta, Mikkel Baun Kjærgaard, Mani Srivastava, and Kamin Whitehouse.

or DOI in the last line.
## Presentations
I think people who attended the talks should be able to find those presentions on the website. Besides, every resource that people can use as a reference should be on this page. We should definitely add the presentations and their venues (if any) next to the presentation titles.

## Static files
I recently fixed a bug related to file linking. For now, you can just leave them as links. I'll make sure I add the files to the repo. 

[6]: https://brickschema.org/papers/Brick-BuildSys2016.pdf

**Comment by gtfierro** [comment]
I pushed some changes addressing your comments. The file linking works now, thanks!

I tried formatting the publication citations using blockquote and it looked a little awkward because it was hard to tell if the citation belonged to the title above or below. Its a little better now, but I'm considering adding a horizontal line between publications to differentiate them. They're now in reverse chronological order as well

**Comment by shreyasnagare** [comment]
This looks great! Is this ready to merge in?

**Comment by gtfierro** [comment]
Yep!

**Pull request merged**
