### PR TITLE
Use python to generate ontology docsource

### PR DESCRIPTION
**Pull request by shreyasnagare**
```bash
python generate_doc_src.py
```
Uses configuration from `generate_doc_src.py` to generate JSON files in `./static/ontology' which are then used to load data to the GraphQL layer of the website.

## Dependencies:
- Python 3.6+
- rdflib

### CODE REVIEW

**Comment by shreyasnagare** [comment]
@gtfierro The current version doesn't have anything specific for EntityProperties (look at the preview). I'll create another PR for that later this week. Please make any changes you think are necessary ([v1.2 markdown file](https://github.com/BrickSchema/brick-website/blob/generate-docsrc-with-python/ontologyPages/v1.2.md)) before pulling this in.

**Comment by shreyasnagare** [comment]
@gtfierro I'm updating the NodeJS version on the server to the latest stable release. Expect some delay in deployment.

**Comment by gtfierro** [comment]
Nice work @shreyasnagare! I changed the v1.2 doc to contain the release notes rather than duplicating the README file like we had before. After the tests pass and I browse some of the generated documentation I will likely merge

**Comment by shreyasnagare** [comment]
@gtfierro Updated NodeJS to the current release: builds should be slightly faster now + no memory errors. Let me know if this PR needs any more changes.

**Pull request merged**
