### PR TITLE
Fix + point to Concepts page

### PR DESCRIPTION
**Pull request by gtfierro**
The concepts page got hidden at some point. I linked to it from the "Get Started" page and fixed the image links. This addresses https://github.com/BrickSchema/brick-website/issues/24 and https://github.com/BrickSchema/brick-website/issues/23

### CODE REVIEW

**Comment by gtfierro** [comment]
Thanks for fixing the links; the "development" site needed the images in a different location, which is what broke the build.

**Comment by shreyasnagare** [comment]
> Thanks for fixing the links; the "development" site needed the images in a different location, which is what broke the build.

I hope that bug gets fixed soon.

It's a better idea to put the images nearer to the markdown files (and use relative ../ links). 
This would
- work consistently for both the development and built versions
- allow other markdown processors (GitHub, IDEs) to show the images with no issues

**Comment by gtfierro** [comment]
Would you be able to address the bug? I can file a separate issue for that if it helps

**Comment by shreyasnagare** [comment]
> Would you be able to address the bug? I can file a separate issue for that if it helps

There is a slight inconsistency in the error reporting in the "develop" and "build" scripts of gridsome. I'll be watching the conversations on the similar issues already present on the dependency's repo. If the maintainers don’t fix this soon, I’ll give it a shot.

**Comment by gtfierro** [comment]
Oh! I didn't realize it was upstream, sorry. Hope they fix it soon :)

**Pull request merged**
