### PR TITLE
Concept Page

### PR DESCRIPTION
**Pull request by gtfierro**
I've taken a stab at writing a high-level concepts page. Its mostly the definitions of the terms that we use and an overview of the design principles, but it is a start. I think its important to organize the information in the concepts page in a way that contributes to the edification of the users.

I wouldn't say the page is finished, but I wanted to get feedback on the page so far.

After we get this decided upon, then we can expand the concepts page to cover the class hierarchy and relationships.

### CODE REVIEW

**Comment by shreyasnagare** [comment]
Simple and lucid. You did a great job with this page, @gtfierro. 

Here's my feedback:
- The node-edge-graph image would look better if it were center-aligned.`node edge graph example{class="mx-auto"}`. 
**Not that important:** You can also make it a little bit smaller by using `{class="mx-auto w-10/12"}` instead (`w-x/12` where x ∈ {1, 2, ..., 11}).
- Simple diagrams (like `node-edge-graph` and `building-model-example`) can be outside the collapsible details. I don't think of them as _too much detail_ and they make the textual page a little more colorful (without expanding). I'm not so sure about the `building-model-example` image but `node-edge-graph` can certainly be outside.
- <details><summary>Expand for detail...</summary></details> can be changed to <details><summary>Learn more</summary></details> or <details><summary>Click for more details</summary></details>
- **Expressivity:** Should "_without expanding the schema too much._" be a part of the expressivity explanation? A schema can be considered expressive even if it is huge. I understand that Brick does this in a very efficient manner (more expressiveness without expanding too much) but I'm not sure if that counts towards the design principle "A schema should be expressive". I'm probably wrong. I just need some clarification.

**Comment by gtfierro** [comment]
Thanks for the thoughtful feedback! I've just pushed some changes to address them.

- center aligned the figure and shrunk it a little bit
- changed the `<summary>` tag to be `Learn more`
- clarified the comment around expressivity. You're right that a schema can be expressive even if it is large :). Let me know what you think of the new statement

**Comment by shreyasnagare** [comment]
The new statement is pretty accurate. You can look at a preview [here](https://brickschema.netlify.com/concepts/). The last expandable detail is kinda useless. :P We can remove it.

**Comment by gtfierro** [comment]
I added some text to the last section so this should be good to merge now

**Pull request merged**
