### PR TITLE
Add Brickly site

### PR DESCRIPTION
**Pull request by ezrichards**

### CODE REVIEW

**Comment by epaulson** [comment]
Hrm, I'm not sure why the build failed. It worked locally for me, so maybe this was just a temporary hiccup, or else maybe there's a difference in the environment netlify is using to build with. I'll take a more detailed look next week - but just as a quick test, could you take out the 'query' tag for your category and push an update? I don't _think_ it should matter, but this is the first tool that uses 'query' as a category so it would be interesting to see if for some odd reason that does make a difference.

**Comment by gtfierro** [comment]
I think I'm actually getting the same error as netlify when I try locally (@epaulson are you doing `npm run develop` or `npm run build`? The latter fails for me). I'll play with it over the weekend but I so far I can't figure out what is wrong

@shreyasnagare if you have some time after the semester is over, can you take a look?

**Comment by shreyasnagare** [comment]
I made some minor changes. Is this PR ready to be merged in?

**Comment by ezrichards** [comment]
@shreyasnagare is this supposed to be happening with the code block? Looks like it's just changing the format of each line of text.
Screen Shot 2022-05-14 at 6 24 58 AM

**Comment by shreyasnagare** [comment]
> @shreyasnagare is this supposed to be happening with the code block? Looks like it's just changing the format of each line of text. Screen Shot 2022-05-14 at 6 24 58 AM

@ezrichards https://github.com/BrickSchema/brick-website/pull/152 should fix this.

**Comment by epaulson** [comment]
I'm still confused about why the deploy-preview works now but failed earlier/why npm run build fails for Gabe?

**Comment by shreyasnagare** [comment]
> I'm still confused about why the deploy-preview works now but failed earlier/why npm run build fails for Gabe?

The markdown metadata for brickly pointed to an image file that did not exist when Gabe tried to generate the website (`brickly.png`). I renamed `blockly.png` to `brickly.png` which essentially fixed the null pointer error.

**Review by epaulson — APPROVED** [review]
Looks good, and will look better once the other changes land for codeblock styling.

**Comment by gtfierro** [comment]
Merged! Thanks @shreyasnagare and @epaulson for helping, and great work @ezrichards on the query tool

**Pull request merged**
