### PR TITLE
Add table, image to about page

### PR DESCRIPTION
**Pull request by gtfierro**
Added one of the figures to the 'about' page that has a high-level example of a Brick model.

Added a small table showing how Brick compares to other efforts in terms of what they are able to model. I don't think this is 100% ready to merge in, but it would be great to get feedback on what people think

### CODE REVIEW

**Comment by shreyasnagare** [comment]
I have merged and [deployed](https://brick.andrew.cmu.edu) your changes (along with horizontal-app-cards). I know it's not complete but it's better than the current version. Everything looks good. Where are we gonna use the [second image](/BrickSchema/brick-website/blob/master/webpages/images/brick-model-example.png)? 

I noticed that  you intentionally used this:
>> **Project Haystack** ([link](https://project-haystack.org/)) is a popular tagging system for...

instead of this:
>>  [**Project Haystack**](https://project-haystack.org/) is a popular tagging system for

What was the reason for that?

**Comment by gtfierro** [comment]
Thanks!  The horizontal app cards look much more like I had in mind. Only thing is the page content is a little narrow for me. Will it expand naturally when we add more text to the app descriptions?

I think the second image belongs on a page that walks through how the class hierarchy works; wasn't sure if that belongs on the main page, but maybe we could place it off to the side with a short caption.

I generally do links like that out of habit; I don't mind if you change it so the anchor tag covers the name of the metadata scheme.

**Comment by shreyasnagare** [comment]
I'm glad you like it. I have made some changes to [the website](https://brick.andrew.cmu.edu/). I hope this makes the content look better.

**Comment by gtfierro** [comment]
I think it looks great! Thanks for making the changes

**Pull request merged**
