### PR TITLE
add tech concept page

### PR DESCRIPTION
**Pull request by jbkoh**
The tables are broken though they work fine with other markdown editors. I don't know why but will take a look. I still need to fill out the contents especially for class construction, but I'm happy to have reviews.

### CODE REVIEW

**Comment by gtfierro** [comment]
Can you leave a comment when its ready for review?

**Comment by shreyasnagare** [comment]
I'm unable to see some tables even on GitHub. I think `newline` should fix this issue. (probably the other issues as well). Try adding `newline` characters before the things that you think are broken.

Screen Shot 2019-07-29 at 6 07 21 PM

**Comment by jbkoh** [comment]
@gtfierro , this PR is ready except the Tags construction rules. I was trying to put some explanation but the example of Zone/Temperature/Sensor being Zone_Temperature_Sensor reads too naive. I can go with that, but I'd appreciate if you can flesh out that part more. Of course, I'd welcome any other comments too.

**Comment by jbkoh** [comment]
I know @gtfierro has some comments but I think we should merge this one and develop further.

**Comment by jbkoh** [comment]
@gtfierro Note that this PR also adds a section to Get Started.
@shreyasnagare Please merge this one when you find time. We can further update later.

**Comment by gtfierro** [comment]
I can try to take a pass through tomorrow morning but the language/grammar
on this page needs work before we merge it in. Please hold off for now

**Pull request closed without merging**
